{ lib, system, self, archerusPkgs, ... }:

let
    _lib = lib;
in

{ config, options, pkgs, lib, ... }:

let
    htmlFile = pkgs.writeText "index.html";
    architectureDiagram = _lib.mkArchitecture {
        ports = config.networking.firewall.allowedTCPPorts;
        vhosts = config.skade.docs.vhosts;
        format = "png";
    };
    docs = _lib.mkOptionsHtml (options.skade);
    webserver = _lib.mkWebServer rec {
        routes = {
            "/" = htmlFile ''
                <!DOCTYPE HTML>
                <html style="text-align: center">
                    <h1>NixOS Autogenerated pages</h1>
                    Despite the name of this page, it just contains some architecture things, static(ish) files that are generated by my nixos infrastructure, and autogenerated docs for my nixos options
                    I've made this autogenerated docs to help myself extend this setup years down in the future.

                    This means, that while i'm happy that other people are reading this page, it is entirely intended for only me to read.
                    ${builtins.concatStringsSep "\n" (map (page: "<a href=\"${page}\">${page}</a><br>") (builtins.attrNames routes))}
                </html>
            '';
            "/Architecture" = htmlFile ''
                <!DOCTYPE HTML>
                <html style="text-align: center">
                    <h1>Architecture</h1>
                    <img src="architecture-diagram.png">
                </html>
            '';
            "/Options" = htmlFile docs;
            "/fklub" = htmlFile ''
                <!DOCTYPE HTML>
                <html>
                    Download the new and exciting NixOS based distribution for the F-klub! (It's not really a distribution as it just installs regular NixOS flakes)
                    
                    Though it does make it very nice and easy to install a flake.
                    <h1>F-NixOS</h1>
                    <a href="F-NixOS.iso">F-NixOS ISO image</a>
                </html>
            '';
            "/ModdedMinecraft" = htmlFile ''
                <!DOCTYPE HTML>
                <html>
                    This is just a short page to download my minecraft modpack.<br>
                    <a href="modded.skade.dev.json">Download import list for prismlauncher</a>
                </html>
            '';
        };
        port = 8095;
        extra_files = {
            "/architecture-diagram.png" = {
                path = architectureDiagram;
                type = "image/png";
            };
            #"/F-NixOS.iso" = {
            #    path = "${archerusPkgs.fNixos}/iso/${archerusPkgs.fNixos.isoName}";
            #    type = "application/x-iso9660-image";
            #};
            "/modded.skade.dev.json" = {
                path = pkgs.writeText "modded.skade.dev.json" (builtins.toJSON [
                    {
                        name = "Botarium";
                        version = "2.3.4";
                    }
                    {
                        name = "Create";
                        version = "0.5.1-j-build.1631+mc1.20.1";
                    }
                    {
                        name = "Create Crafts & Additions";
                        version = "NONE";
                    }
                    {
                        name = "Create Enchantment Industry";
                        version = "1.2.16";
                    }
                    {
                        name = "Create Nuclear";
                        version = "1.20.1";
                    }
                    {
                        name = "Create Ore Excavation";
                        version = "1.5.4";
                    }
                    {
                        name = "Create: New Age";
                        version = "1.1.2";
                    }
                    {
                        name = "Create: Steam 'n' Rails";
                        version = "1.6.9+fabric-mc1.20.1";
                    }
                    {
                        name = "Create: Structures";
                        version = "1.1.0";
                    }
                    {
                        name = "Fabric API";
                        version = "0.92.6+1.20.1";
                    }
                    {
                        name = "Indium";
                        version = "1.0.36+mc1.20.1";
                    }
                    {
                        name = "Iris";
                        version = "1.7.6+mc1.20.1";
                    }
                    {
                        name = "Iris Flywheel Compat";
                        version = "1.1.4";
                    }
                    {
                        name = "Jade";
                        version = "11.13.1+fabric";
                    }
                    {
                        name = "Just Enough Items";
                        version = "15.20.0.116";
                    }
                    {
                        name = "MaLiLib";
                        version = "0.16.3";
                    }
                    {
                        name = "MiniHUD";
                        version = "0.27.1";
                    }
                    {
                        name = "Sodium";
                        version = "0.5.13+mc1.20.1";
                    }
                    {
                        name = "WaylandFix";
                        version = "1.1";
                    }
                    {
                        name = "Xaero's Minimap";
                        version = "25.2.10";
                    }
                    {
                        name = "Fabric Language Kotlin";
                        version = "1.13.7+kotlin.2.2.21";
                    }
                    {
                        name = "Create: Power Loader";
                        version = "1.5.3-mc1.20.1-fabric";
                    }
                    {
                        name = "Create Jetpack";
                        version = "4.3.0";
                    }
                ]);
                type = "text/plain";
            };
        };
    };
in

{
    options.skade.docs = {
        vhosts = lib.mkOption {
            type = lib.types.attrs;
            default = {};
            description = ''
                Attrset of data about a virtualhost
            '';
        };
    };
    config = _lib.mkWebProject config {
        name = "docs";
        exec = "${webserver}/bin/nix-webserver";
        port = 8095;
    };
}
