{
  imports = [
      ./minecraft.nix
      ./Putricide.nix
      ./WOL-bot.nix
      ./jupyter.nix
      ./mysql.nix
      ./vpn.nix
      ./lavalink.nix
      ./SketchBot.nix
      ./nginx.nix
      ./vnc.nix
      ./nextcloud.nix
      ./supertuxkart.nix
      ./ssh.nix
      ./wordcount.nix
      ./website.nix
  ];
}
