name: Build packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: build packages
        run: |
          for package in comicMonoLiga electronApps.chatgpt electronApps.fikien electronApps.nixosSearch electronApps.stregsystemet electronApps.youtube fPlymouthTheme folkevognen homepage initializer libarcherus prefix putricide rp-utils warcraftLogsUploader webserver; do
            nix build .\#packages.x86_64-linux.$package
          done
