name: evaluate nix store paths

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: evaluate systems
        run: |
          for system in Arcueid Kohaku Skademaskinen; do
            nix eval .#nixosConfigurations.$system.config.system.build.toplevel
          done
