name: evaluate nix store paths

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        output: ["nixosConfigurations.arcueid"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Nix cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: build system
        run: nix eval .#${{ matrix.output }}.config.system.build.nixos
