name: Test NixOS configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
o  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      
      - name: build-backend
        run: nix build -f ./packages/backend.nix
      - name: build-putricide
        run: nix build -f ./packages/putricide.nix
      - name: build-banner
        run: nix build -f ./packages/banner.nix
