name: Test NixOS configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      
      - name: build-warcraftlogsuploader
        run: nix build .#warcraftlogsuploader
      - name: build-all
        run: nix build .#skademaskinen
