name: Test NixOS configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      
      - name: prepare
        run: sudo sh <(curl -L https://nixos.org/nix/install) --daemon
      - name: nix-channel
        run: sudo nix-channel --add https://nixos.org/channels/nixos-23.11 && sudo nix-channel --update
        
      - name: build-backend
        run: sudo nix --extra-experimental-features "nix-command flakes" build -f ./packages/backend.nix
      - name: build-putricide
        run: sudo nix --extra-experimental-features "nix-command flakes" build -f ./packages/putricide.nix
      - name: build-skademaskinen
        run: sudo nix --extra-experimental-features "nix-command flakes" shell nixpkgs#nixos-rebuild --command nixos-rebuild build-vm --flake .#Skademaskinen
      - name: build-laptop
        run: sudo nix --extra-experimental-features "nix-command flakes" shell nixpkgs#nixos-rebuild --command nixos-rebuild build-vm --flake .#laptop
      - name: build-desktop
        run: sudo nix --extra-experimental-features "nix-command flakes" shell nixpkgs#nixos-rebuild --command nixos-rebuild build-vm --flake .#desktop
